apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amrutam-api-ingress
  namespace: amrutam
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: amrutam.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: amrutam-api
                port:
                  number: 80
